# Generated by Django 4.2.24 on 2025-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField(default=0)),
                ('descripcion', models.CharField(default='', max_length=256)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
